/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ZVote } from './ZVote.js';
export * as factories from './factories/index.js';
export { ZVote__factory } from './factories/ZVote__factory.js';