/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ZVoteInterface extends Interface {
    getFunction(nameOrSignature: "addCandidate" | "createPosition" | "electionActive" | "electionAuthority" | "electionName" | "endElection" | "getCandidateCount" | "getPositionTitle" | "getResults" | "hasVoted" | "positionCount" | "startElection" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CandidateAdded" | "ElectionEnded" | "ElectionStarted" | "PositionCreated" | "VoteCast"): EventFragment;

    encodeFunctionData(functionFragment: 'addCandidate', values: [BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'createPosition', values: [string]): string;
encodeFunctionData(functionFragment: 'electionActive', values?: undefined): string;
encodeFunctionData(functionFragment: 'electionAuthority', values?: undefined): string;
encodeFunctionData(functionFragment: 'electionName', values?: undefined): string;
encodeFunctionData(functionFragment: 'endElection', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCandidateCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPositionTitle', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getResults', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'positionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'startElection', values: [string]): string;
encodeFunctionData(functionFragment: 'vote', values: [AddressLike, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPosition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'electionActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'electionAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'electionName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidateCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPositionTitle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getResults', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'positionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace CandidateAddedEvent {
      export type InputTuple = [positionId: BigNumberish, candidateId: BigNumberish, name: string, programme: string];
      export type OutputTuple = [positionId: bigint, candidateId: bigint, name: string, programme: string];
      export interface OutputObject {positionId: bigint, candidateId: bigint, name: string, programme: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionEndedEvent {
      export type InputTuple = [electionName: string];
      export type OutputTuple = [electionName: string];
      export interface OutputObject {electionName: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionStartedEvent {
      export type InputTuple = [electionName: string];
      export type OutputTuple = [electionName: string];
      export interface OutputObject {electionName: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PositionCreatedEvent {
      export type InputTuple = [positionId: BigNumberish, title: string];
      export type OutputTuple = [positionId: bigint, title: string];
      export interface OutputObject {positionId: bigint, title: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [voter: AddressLike, positionId: BigNumberish, candidateId: BigNumberish];
      export type OutputTuple = [voter: string, positionId: bigint, candidateId: bigint];
      export interface OutputObject {voter: string, positionId: bigint, candidateId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ZVote extends BaseContract {
    
    connect(runner?: ContractRunner | null): ZVote;
    waitForDeployment(): Promise<this>;

    interface: ZVoteInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCandidate: TypedContractMethod<
      [_positionId: BigNumberish, _name: string, _programme: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    createPosition: TypedContractMethod<
      [_title: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    electionActive: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    electionAuthority: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    electionName: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    endElection: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getCandidateCount: TypedContractMethod<
      [_positionId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getPositionTitle: TypedContractMethod<
      [_positionId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getResults: TypedContractMethod<
      [_positionId: BigNumberish, ],
      [[string[], string[], bigint[]] & {names: string[], programmes: string[], voteCounts: bigint[] }],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [_voter: AddressLike, _positionId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    positionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    startElection: TypedContractMethod<
      [_electionName: string, ],
      [void],
      'nonpayable'
    >
    

    
    vote: TypedContractMethod<
      [_voter: AddressLike, _positionId: BigNumberish, _candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCandidate'): TypedContractMethod<
      [_positionId: BigNumberish, _name: string, _programme: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPosition'): TypedContractMethod<
      [_title: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'electionActive'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'electionAuthority'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'electionName'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'endElection'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCandidateCount'): TypedContractMethod<
      [_positionId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPositionTitle'): TypedContractMethod<
      [_positionId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getResults'): TypedContractMethod<
      [_positionId: BigNumberish, ],
      [[string[], string[], bigint[]] & {names: string[], programmes: string[], voteCounts: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [_voter: AddressLike, _positionId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'positionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'startElection'): TypedContractMethod<
      [_electionName: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [_voter: AddressLike, _positionId: BigNumberish, _candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CandidateAdded'): TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
getEvent(key: 'ElectionEnded'): TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
getEvent(key: 'ElectionStarted'): TypedContractEvent<ElectionStartedEvent.InputTuple, ElectionStartedEvent.OutputTuple, ElectionStartedEvent.OutputObject>;
getEvent(key: 'PositionCreated'): TypedContractEvent<PositionCreatedEvent.InputTuple, PositionCreatedEvent.OutputTuple, PositionCreatedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;

    filters: {
      
      'CandidateAdded(uint256,uint256,string,string)': TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
      CandidateAdded: TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
    

      'ElectionEnded(string)': TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
      ElectionEnded: TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
    

      'ElectionStarted(string)': TypedContractEvent<ElectionStartedEvent.InputTuple, ElectionStartedEvent.OutputTuple, ElectionStartedEvent.OutputObject>;
      ElectionStarted: TypedContractEvent<ElectionStartedEvent.InputTuple, ElectionStartedEvent.OutputTuple, ElectionStartedEvent.OutputObject>;
    

      'PositionCreated(uint256,string)': TypedContractEvent<PositionCreatedEvent.InputTuple, PositionCreatedEvent.OutputTuple, PositionCreatedEvent.OutputObject>;
      PositionCreated: TypedContractEvent<PositionCreatedEvent.InputTuple, PositionCreatedEvent.OutputTuple, PositionCreatedEvent.OutputObject>;
    

      'VoteCast(address,uint256,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    
    };
  }